// /*
//  * @author Borja Lorente Escobar
//  * Copyright 2015
//  */
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace KWorks.Wrappers
{
	public static class Rigidbody2DWrapper
	{
		public static void SetVelocityX(this Rigidbody2D rb, float newX) {
			Vector2 newVelocity = 
				new Vector2(newX, rb.velocity.y);
			
			rb.velocity = newVelocity;
		}

		public static void SetVelocityY(this Rigidbody2D rb, float newY) {
			Vector2 newVelocity = 
				new Vector2(rb.velocity.x, newY);
			
			rb.velocity = newVelocity;
		}

        public static void SetVelocity2D(this Rigidbody2D rb, Vector2 newVel)
        {           
            rb.velocity = newVel;
        }

        public static void SetVelocity2D(this Rigidbody2D rb, float newX, float newY)
        {
            Vector2 newVelocity =
                new Vector2(newX, newY);

            rb.velocity = newVelocity;
        }

		public static void AddVerticalForce(this Rigidbody2D rb, float force) {
			rb.AddForce(new Vector3(0, force, 0));
		}

		public static void AddHorizontalForce(this Rigidbody2D rb, float force) {
			rb.AddForce(new Vector3(force, 0, 0));
		}
	}
}

